/*
 * mcal_interrupt_gen_cfg.h
 *
 *  Created on: Sep 18, 2023
 *      Author: hazem
 */

#ifndef MCAL_LAYER_INTERRUPT_MCAL_INTERRUPT_GEN_CFG_H_
#define MCAL_LAYER_INTERRUPT_MCAL_INTERRUPT_GEN_CFG_H_

#define INTERRUPT_FEATURE_ENABLE 1
#define EXTERNAL_INTERRUPT_FEATURE_ENABLE 		INTERRUPT_FEATURE_ENABLE
#define ADC_INTERRUPT_FEATURE_ENABLE 	INTERRUPT_FEATURE_ENABLE


#endif /* MCAL_LAYER_INTERRUPT_MCAL_INTERRUPT_GEN_CFG_H_ */
